export const API_ENDPOINTS = {
  auth: {
    login: '/api/auth/login',
    register: '/api/auth/register',
    refresh: '/api/auth/refresh',
    logout: '/api/auth/logout',
    forgotPassword: '/api/auth/forgot-password',
    resetPassword: '/api/auth/reset-password',
  },
  users: {
    me: '/api/users/me',
    info: '/api/users/me/info',
  },
  modules: {
    available: '/api/modules/available',
  },
  categories: {
    root: '/api/categories',
    detail: (categoryId: string) => `/api/categories/${categoryId}`,
    status: (categoryId: string) => `/api/categories/${categoryId}/status`,
  },
  products: {
    root: '/api/products',
    detail: (productId: string) => `/api/products/${productId}`,
    status: (productId: string) => `/api/products/${productId}/status`,
  },
  tables: {
    root: '/api/tables',
    detail: (tableId: string) => `/api/tables/${tableId}`,
    operation: '/api/tables/operation',
    operationState: (tableId: string) => `/api/tables/${tableId}/operation`,
    order: (tableId: string) => `/api/tables/${tableId}/order`,
    areas: {
      root: '/api/table-areas',
      detail: (areaId: string) => `/api/table-areas/${areaId}`,
      reorder: '/api/table-areas/reorder',
    },
  },
  orders: {
    root: '/api/orders',
    items: '/api/orders/items',
    activeByTable: (tableId: string) => `/api/orders/table/${tableId}/active`,
    addItems: (tableId: string) => `/api/orders/table/${tableId}/items`,
    moveTable: (tableId: string) => `/api/orders/table/${tableId}/move`,
    cancelItem: (itemId: string) => `/api/orders/items/${itemId}/cancel`,
    checkout: (tableId: string) => `/api/orders/table/${tableId}/checkout`,
    summaryReceipt: (orderId: string) => `/api/orders/${orderId}/receipts/summary`,
    receipts: (orderId: string) => `/api/orders/${orderId}/receipts`,
  },
  inventory: {
    root: '/api/inventory',
    ingredients: {
      root: '/api/inventory/ingredients',
      detail: (ingredientId: string) => `/api/inventory/ingredients/${ingredientId}`,
      status: (ingredientId: string) => `/api/inventory/ingredients/${ingredientId}/status`,
    },
    movements: '/api/inventory/movements',
    complements: {
      units: '/api/inventory/complements/units',
      unit: (unitId: string) => `/api/inventory/complements/units/${unitId}`,
      unitStatus: (unitId: string) => `/api/inventory/complements/units/${unitId}/status`,
    },
  },
  settings: {
    organization: '/api/settings/organization',
    organizationLogo: '/api/settings/organization/logo',
    business: '/api/settings/business',
    paymentMethods: '/api/settings/payment-methods',
    paymentMethod: (paymentMethodId: string) => `/api/settings/payment-methods/${paymentMethodId}`,
    paymentMethodStatus: (paymentMethodId: string) =>
      `/api/settings/payment-methods/${paymentMethodId}/status`,
    access: {
      permissions: '/api/settings/access/permissions',
      roles: '/api/settings/access/roles',
      role: (roleId: string) => `/api/settings/access/roles/${roleId}`,
      roleStatus: (roleId: string) => `/api/settings/access/roles/${roleId}/status`,
      users: '/api/settings/access/users',
      user: (entryId: string) => `/api/settings/access/users/${entryId}`,
    },
  },
  tenants: {
    root: '/api/tenants',
    select: (tenantId: string) => `/api/tenants/${tenantId}/select`,
  },
  cashRegisters: {
    root: '/api/cash-registers',
    detail: (cashRegisterId: string) => `/api/cash-registers/${cashRegisterId}`,
    status: (cashRegisterId: string) => `/api/cash-registers/${cashRegisterId}/status`,
    openShift: '/api/cash-registers/shifts/open',
    closeShift: (shiftId: string) => `/api/cash-registers/shifts/${shiftId}/close`,
    shiftSummary: (shiftId: string) => `/api/cash-registers/shifts/${shiftId}/summary`,
    shiftsPage: '/api/cash-registers/shifts',
  },
  suppliers: {
    root: '/api/suppliers',
    lookup: '/api/suppliers/lookup',
    detail: (supplierId: string) => `/api/suppliers/${supplierId}`,
    status: (supplierId: string) => `/api/suppliers/${supplierId}/status`,
  },
  expenses: {
    root: '/api/expenses',
    detail: (expenseId: string) => `/api/expenses/${expenseId}`,
    annul: (expenseId: string) => `/api/expenses/${expenseId}/annul`,
  },
  digitalMenu: {
    config: '/api/digital-menu/config',
    parameters: '/api/digital-menu/parameters',
    items: '/api/digital-menu/items',
    style: '/api/digital-menu/style',
    public: (slug: string) => `/api/public/menu/${encodeURIComponent(slug)}`,
  },
  printing: {
    configuration: '/api/printing/configuration',
    locations: '/api/printing/locations',
    routingOptions: '/api/printing/routing-options',
    agents: '/api/printing/agents',
    discoveredAgents: '/api/printing/agents/discovered',
    linkDiscoveredAgent: '/api/printing/agents/link-discovered',
    agent: (agentId: string) => `/api/printing/agents/${agentId}`,
    pairingCodes: '/api/printing/agents/pairing-codes',
    printers: '/api/printing/printers',
    agentPrinters: (agentId: string) => `/api/printing/agents/${agentId}/printers`,
    availablePrinters: (agentId: string) => `/api/printing/agents/${agentId}/available-printers`,
    discoverPrinters: (agentId: string) => `/api/printing/agents/${agentId}/discover-printers`,
    printer: (printerId: string) => `/api/printing/printers/${printerId}`,
    testPrint: (agentId: string) => `/api/printing/agents/${agentId}/test-print`,
    zones: '/api/printing/zones',
    zone: (zoneId: string) => `/api/printing/zones/${zoneId}`,
    jobs: '/api/printing/jobs',
    cancelJob: (jobId: string) => `/api/printing/jobs/${jobId}/cancel`,
    retryJob: (jobId: string) => `/api/printing/jobs/${jobId}/retry`,
    reprintJob: (jobId: string) => `/api/printing/jobs/${jobId}/reprint`,
  },
  i18n: {
    language: (language: string) => `/api/i18n/${language}`,
  },
} as const;
