name: Build, publish and deploy frontends

on:
  push:
    branches:
      - dev
      - qa
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  admin:
    name: Admin frontend
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/frontend-component.yml
    with:
      image_name: saviaup-frontend
      angular_project: savia-up-web
      dist_project: savia-up-web
      component_path: frontend
      deployment_name: frontend
      apply_ingress: false
    secrets: inherit

  public-menu:
    name: Public menu frontend
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/frontend-component.yml
    with:
      image_name: saviaup-frontend-menu
      angular_project: saviaup.frontend-menu
      dist_project: saviaup.frontend-menu
      component_path: frontend-menu
      deployment_name: frontend-menu
      apply_ingress: true
    secrets: inherit
